### ISSUE TITLE
Add support for Zilliqa mining, dualmining and staking

### ISSUE THREAD

**Issue by oliverw** [oliverw/miningcore#1202]
### Discussed in https://github.com/oliverw/miningcore/discussions/1171

<div type='discussions-op-text'>

<sup>Originally posted by **ei8ht187** February 20, 2022</sup>
Many Miners offers the possibility to dualmine Ethereum and Zilliqa. Beside mining, Zilliqa also uses PoS. Therefore, it be great when Miningcore supports this features too. 

As far as I understood the Zilliqa documentation, the miningpart is based on ethash. Probably, this would be easy to implement :). </div>

**Comment by seperatis** [comment]
Should we put any time & energy into this when ETH is going Proof-of-Stake in about 25 days?
Just a thought.

**Comment by ei8ht187** [comment]
Well, many pools are looking for alternatives like Ethereum Classic, Ziliqa, Callisto. Maybe ditch ETH and add ETC besides Zilliqa.
Dual Mining would be an option with the pairs CLO+ZIL and ETC+ZIL.

**Comment by Dismenol** [comment]
> Should we put any time & energy into this when ETH is going Proof-of-Stake in about 25 days? Just a thought.

well, ZIL is getting mined just for a few seconds each hour. so ZIL can be mined by side any other coin/chain, as it opens up a completely new connection once the proxy/stratum announces some work (on lolminer it is listening).

So ZIL won't die and has nothing to do with ETH going 2.0

**Comment by seperatis** [comment]
> > Should we put any time & energy into this when ETH is going Proof-of-Stake in about 25 days? Just a thought.
> 
> well, ZIL is getting mined just for a few seconds each hour. so ZIL can be mined by side any other coin/chain, as it opens up a completely new connection once the proxy/stratum announces some work (on lolminer it is listening).
> 
> So ZIL won't die and has nothing to do with ETH going 2.0

I never said anything about ZIL dying. I said it's not worth spending time to make ETH/ZIL mining part of Miningcore since ETH will be POS in (now) a couple days; which means ETH PoW mining will no longer be supported/possible.

ETC/ZIL sure.

I don't know about "along-side" **any** other coin. @ei8ht187 said he thought the PoW component was based on ethash. If that's true, then it only make sense to do it alongside other similar algos. 

I haven't looked at it, so I have no idea.

It might open up a complete new connection, but it's not going to adjust for a person's current OC settings on their mining rig which are tuned for KawPow or any other handful of algos.
